export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'; 
export const PRODUCT_DE_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_DE_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_DE_FAIL = 'PRODUCT_LIST_FAIL'; 